{ pkgs, ... }:

{
  programs.waybar = {
    enable = true;

    settings = {
      mainBar = {
        layer = "top";
        position = "top";
        height = 26;
        modules-left = [ "hyprland/workspaces" ];
        modules-center = [ "clock" ];
        modules-right = [
          "battery"
          "pulseaudio"
          "tray"
        ];

        "hyprland/workspaces" = {
          disable-scroll = true;
          all-outputs = true;
          format = "{name}";

          show-special = true;
          special-visible-only = true;
        };
        clock = {
          format = "{:%H:%M - %d/%m/%Y}";
        };
        battery = {
          format = "{capacity}%";
        };
        pulseaudio = {
          format = "VOL {volume}%";
        };
      };
    };

    style = ''
            * {
      border: none;
              border-radius: 0;
              font-family: monospace;
              font-size: 13px;
              min-height: 0;
            }
          window#waybar {
      background: #000000;
      color: #ffffff;
             border-bottom: 1px solid #333333; /* Thin outline */
          }
      #workspaces button {
      padding: 0 5px;
      background: transparent;
      color: #888888;
      }
      #workspaces button.active {
      color: #ffffff;
      background: #333333;
      }
      #clock, #battery, #pulseaudio, #tray {
      padding: 0 10px;
      color: #ffffff;
      }
    '';
  };

  wayland.windowManager.hyprland = {
    enable = true;
    package = null;

    settings = { };

    extraConfig = ''
        hl.config({ autogenerated = false })

        ------------------
        ---- MONITORS ----
        ------------------
        hl.monitor({
            output   = "HDMI-A-1",
            mode     = "1920x1080@75",
            position = "0x0",
            scale    = "1",
          })
        hl.monitor({
            output   = "eDP-2",
            mode     = "1920x1200@165",
            position = "1920x0",
            scale    = "1",
          })

          hl.workspace_rule({ workspace = "1", monitor = "HDMI-A-1", default = true })
          hl.workspace_rule({ workspace = "2", monitor = "HDMI-A-1" })
          hl.workspace_rule({ workspace = "3", monitor = "HDMI-A-1" })
          hl.workspace_rule({ workspace = "4", monitor = "eDP-2", default = true })

        ---------------------
        ---- MY PROGRAMS ----
        ---------------------
        local mod = "SUPER"
        local term = "kitty"
        local menu = "wofi --show drun"
        local fileManager = "dolphin"

        -------------------
        ---- AUTOSTART ----
        -------------------
        hl.on("hyprland.start", function ()
            hl.exec_cmd("swaybg -i /home/tomasxs/.local/share/wallpaper/dark1.jpg -m fill")
            hl.exec_cmd("waybar")
            hl.exec_cmd("mako")
            hl.exec_cmd("hypridle") -- Starts the background tracker for sleep/lock

            -- 2. Applications (launched silently on their assigned workspaces)
            hl.exec_cmd("[workspace 1 silent] helium-browser")

            hl.exec_cmd("[workspace 2 silent] kitty")

            hl.exec_cmd("[workspace 3 silent] Telegram")
            -- TODO: fix vesktop loading on wrong monitor
            hl.exec_cmd("[workspace 3 silent] vesktop")

            hl.exec_cmd("[workspace 4 silent] spotify")

            -- hl.exec_cmd("[workspace special:magic silent] zeditor")

        end)

        -----------------------
        ---- LOOK AND FEEL ----
        -----------------------
        hl.config({
          input = {
              kb_layout = "br,us",
              kb_options = "ctrl:nocaps",
              follow_mouse = 1,
              touchpad = {
                  natural_scroll = true,
              },
          },

            general = {
            gaps_in  = 2,
            gaps_out = 0,
            border_size = 1,

            col = {
            active_border   = "rgba(ffffffaa)",
            inactive_border = "rgba(333333aa)",
            },

            layout = "dwindle",
            },

            decoration = {
              rounding = 0,
              active_opacity = 1.0,
              inactive_opacity = 1.0,

              shadow = {
                enabled      = true,
                range        = 4,
                render_power = 3,
                color        = 0xee000000,
              },

              blur = {
                enabled = false,
              },
            },

            animations = {
              enabled = false,
            },
        })

      ---------------------
        ---- KEYBINDINGS ----
        ---------------------
        -- Basic Commands
        hl.bind(mod .. " + RETURN", hl.dsp.exec_cmd(term))
        hl.bind(mod .. " + W", hl.dsp.window.close())
        hl.bind(mod .. " + J", hl.dsp.layout("togglesplit"))
        hl.bind(mod .. " + E", hl.dsp.exec_cmd(fileManager))
        hl.bind(mod .. " + L", hl.dsp.exec_cmd("loginctl lock-session"))
        -- Instantly put the computer to sleep (it will automatically lock first thanks to hypridle)
        hl.bind(mod .. " + SHIFT + L", hl.dsp.exec_cmd("systemctl suspend"))
        -- hl.bind(mod .. " + L", hl.dsp.exec_cmd("hyprlock"))
        hl.bind(mod .. " + D", hl.dsp.exec_cmd(menu))
        hl.bind(mod .. " + P", hl.dsp.window.pseudo())
        hl.bind(mod .. " + F", hl.dsp.window.fullscreen())
        hl.bind(mod .. " + SPACE", hl.dsp.exec_cmd("hyprctl switchxkblayout all next"))
        hl.bind(mod .. " + V", hl.dsp.window.float({ action = "toggle" }))
        hl.bind(mod .. " + ALT + E", hl.dsp.exit())

        -- Move focus
        hl.bind(mod .. " + left",  hl.dsp.focus({ direction = "left" }))
        hl.bind(mod .. " + right", hl.dsp.focus({ direction = "right" }))
        hl.bind(mod .. " + up",    hl.dsp.focus({ direction = "up" }))
        hl.bind(mod .. " + down",  hl.dsp.focus({ direction = "down" }))

        -- Move windows
        hl.bind(mod .. " + SHIFT + left",  hl.dsp.window.move({ direction = "left" }))
        hl.bind(mod .. " + SHIFT + right", hl.dsp.window.move({ direction = "right" }))
        hl.bind(mod .. " + SHIFT + up",    hl.dsp.window.move({ direction = "up" }))
        hl.bind(mod .. " + SHIFT + down",  hl.dsp.window.move({ direction = "down" }))

        -- Workspaces
        for i = 1, 10 do
          local key = i % 10 -- 10 maps to key 0
            hl.bind(mod .. " + " .. key,         hl.dsp.focus({ workspace = i}))
            hl.bind(mod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }))
            end

            -- Special Workspaces
            hl.bind(mod .. " + S",         hl.dsp.workspace.toggle_special("magic"))
            hl.bind(mod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

            -- Mouse scrolling through workspaces
            hl.bind(mod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
            hl.bind(mod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))

            -- Mouse drag/resize
            hl.bind(mod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
            hl.bind(mod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

            -- Media & Brightness
            hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
            hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),      { locked = true, repeating = true })
            hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),     { locked = true, repeating = true })
            hl.bind("XF86AudioMicMute",     hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),   { locked = true, repeating = true })
            hl.bind("XF86MonBrightnessUp",  hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"),                  { locked = true, repeating = true })
            hl.bind("XF86MonBrightnessDown",hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"),                  { locked = true, repeating = true })

            hl.bind("XF86AudioNext",  hl.dsp.exec_cmd("playerctl next"),       { locked = true })
            hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
            hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
            hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd("playerctl previous"),   { locked = true })
    '';
  };
  services.hypridle = {
    enable = true;
    package = null;

    settings = {
      general = {
        lock_cmd = "pidof hyprlock || hyprlock";
        before_sleep_cmd = "loginctl lock-session";
        after_sleep_cmd = "hyprctl dispatch dpms on";
      };

      listener = [
        {
          timeout = 300;
          on-timeout = "loginctl lock-session";
        }
        {
          timeout = 330;
          on-timeout = "hyprctl dispatch dpms off";
          on-resume = "hyprctl dispatch dpms on";
        }
        {
          timeout = 1800;
          on-timeout = "systemctl suspend";
        }
      ];
    };
  };

  programs.hyprlock = {
    enable = true;
    package = null;

    settings = {
      general = {
        disable_loading_bar = true;
        hide_cursor = true;
      };

      background = [
        {
          path = "/home/tomasxs/.local/share/wallpaper/dark1.jpg";
          blur_passes = 3;
          blur_size = 8;
        }
      ];

      input-field = [
        {
          size = "250, 50";
          position = "0, -80";
          monitor = "";
          dots_center = true;
          fade_on_empty = false;
          font_color = "rgb(255, 255, 255)";
          inner_color = "rgb(0, 0, 0)";
          outer_color = "rgb(51, 51, 51)";
          outline_thickness = 2;
          placeholder_text = "<i>Password...</i>";
          shadow_passes = 2;
        }
      ];

      label = [
        {
          text = "$TIME";
          font_size = 64;
          font_family = "JetBrainsMono Nerd Font Bold";
          position = "0, 80";
          valign = "center";
          halign = "center";
          color = "rgb(255, 255, 255)";
        }
      ];
    };
  };

  home.sessionVariables = {
    GTK_THEME = "Adwaita:dark";
  };

  gtk = {
    enable = true;
    theme = {
      name = "Adwaita-dark";
      package = pkgs.gnome-themes-extra;
    };

    gtk3.extraConfig = {
      gtk-application-prefer-dark-theme = 1;
    };
    gtk4.extraConfig = {
      gtk-application-prefer-dark-theme = 1;
    };
  };

  dconf.settings = {
    "org/gnome/desktop/interface" = {
      color-scheme = "prefer-dark";
    };
  };

  qt = {
    enable = true;
    platformTheme.name = "gtk";
    style.name = "adwaita-dark";
    style.package = pkgs.adwaita-qt;
  };

  home.packages = with pkgs; [
    gnome-themes-extra
    adwaita-qt
    mako
    swaybg
    adwaita-icon-theme

    wofi
    pavucontrol
    networkmanagerapplet
  ];
}
